<?php

namespace Setools\Bundle\DbTranslationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TranslationRepository extends EntityRepository
{
    public function getLocalesList()
    {
        $hydratedList = [];
        $list = $this->getEntityManager()
                     ->createQuery(
                         'SELECT t.locale FROM SetoolsDbTranslationBundle:Translation t GROUP BY t.locale ORDER BY t.locale ASC'
                     )
                     ->getArrayResult();
        
        if ($list) {
            foreach ($list as $row) {
                $hydratedList[] = $row['locale'];
            }
        }
        
        return $hydratedList;
    }
}
