parameters:
    setools.translation.loader.db.class: Setools\Bundle\DbTranslationBundle\Services\DbLoader
    translator.class: Setools\Bundle\DbTranslationBundle\Services\Translation\Translator
    
services:
    translation.loader.db:
        class: %setools.translation.loader.db.class%
        arguments: [@doctrine]
        tags:
            - { name: translation.loader, alias: db}

    setools.translation.translator:
        class: Setools\Bundle\DbTranslationBundle\Services\Translation\Translator
        parent: translator.default